### ISSUE TITLE
history.txt file can be saved and read but is not coded

### ISSUE THREAD

**Issue by andreho55** [ivanmalamen/LanChat#11]
1. Open menu “Options” to verify the path to our history file.
1. Open the folder which contains our history file.

2. Open file. 

3. Check the file content.

**Comment by andreho55** [comment]
bug is fixed in v.6

**Comment by andreho55** [comment]
bug is not fixed in v.8
conversation in history.txt is not coded

**Comment by Eugene911111** [comment]
bug is not fixed in v.9
conversation in history.txt is not coded

**Comment by ivanmalamen** [comment]
won't fix
