### ISSUE TITLE
Sniffer captures packets sent from one PC to another. Text of the messages can be read

### ISSUE THREAD

**Issue by andreho55** [ivanmalamen/LanChat#12]
1.	Send message “Hello World!” from VM1 to VM2.
2.	Send message “Hello Hello” from VM2 to VM1.
3.	Open sniffer program. Run live scan process. Check if the program can capture information about our packets.

**Comment by andreho55** [comment]
bug is fixed v.6

**Comment by Eugene911111** [comment]
bug is not fixed in v.0.8
messages are not coded

**Comment by andreho55** [comment]
bug is not fixed in v.0.9
messages are not coded

**Comment by Eugene911111** [comment]
bug is not fixed in v.0.10
 messages are not coded

**Comment by ivanmalamen** [comment]
won't fix
