### ISSUE TITLE
bug_2_When sending the message out of 256 symbols typed 250-252 symbols are only sent to another user

### ISSUE THREAD

**Issue by Alyona2015** [ivanmalamen/LanChat#17]
Steps to reproduce:

1. Choose a dialogue with another PC user

2. Type any 256 symbols.

3. Click “Send”

**Comment by Alyona2015** [comment]
Steps to reproduce:

    1.Choose a dialogue with another PC user

    2.Type any 256 symbols.

    3.Click “Send”

**Comment by Alyona2015** [comment]
Steps to reproduce:
1.Choose a dialogue with another PC user

2.Type any 256 symbols.

3.Click “Send”

**Comment by Alyona2015** [comment]
Open LanChat v.0.8
Steps to reproduce:
1.Choose a dialogue with another PC user

2.Type any 256 symbols.

3.Click “Send”

**Comment by Alyona2015** [comment]
Open LanChat v.0.9
Steps to reproduce:
1.Choose a dialogue with another PC user

2.Type any 256 symbols.

3.Click “Send”

**Comment by Alyona2015** [comment]
Open LanChat v.0.10
Steps to reproduce:
1.Choose a dialogue with another PC user

2.Type any 256 symbols.

3.Click “Send”

**Comment by ivanmalamen** [comment]
won't fix
