### ISSUE TITLE
Bug_8_ The button "Options" doesn't correspond to the name "Settings" from requirements

### ISSUE THREAD

**Issue by Alyona2015** [ivanmalamen/LanChat#23]
Steps to reproduce:

1.Open LanChat 

2. Find button "Settings":-)))

**Comment by Anna040890** [comment]
Steps to reproduce:

1.Open LanChat

    Find button "Settings":-)))

**Comment by Anna040890** [comment]
Steps to reproduce:

1.Open LanChat

    Find button "Settings":-)))

**Comment by Alyona2015** [comment]
Steps to reproduce:

1.Open LanChat v.0.8

2. Find button "Settings":-)))

**Comment by Alyona2015** [comment]
Steps to reproduce:

1.Open LanChat v.0.9

    Find button "Settings":-)))

**Comment by Alyona2015** [comment]
Steps to reproduce:

1.Open LanChat v.0.10

2. Find button "Settings":-)))

**Comment by Alyona2015** [comment]
Bug is fixed in LanChat v.0.11
