### ISSUE TITLE
Program window can't be maximized.

### ISSUE THREAD

**Issue by alinaomelia** [ivanmalamen/LanChat#8]
1. Maximizing button is not active.
2. There is no possibility to change size of the program window.

**Comment by alinaomelia** [comment]
Bug was not fixed.

**Comment by alinaomelia** [comment]
Version 0.8
Bug was not fixed.

**Comment by alinaomelia** [comment]
Version 0.9
Bug was not fixed.

**Comment by ivanmalamen** [comment]
Won't fix

**Comment by alinaomelia** [comment]
Version 0.10
Bug was not fixed.
