### ISSUE TITLE
bug_1_When sending the message out of 255 symbols typed 250-252 symbols are only sent to another user

### ISSUE THREAD

**Issue by Alyona2015** [ivanmalamen/LanChat#9]
Open LanChat v.0.6.
Steps to reproduce:

1. Choose a dialogue with another PC user

2. Type any 255 symbols out of 256. 

3. Click “Send”

**Comment by Alyona2015** [comment]
Steps to reproduce:

   1. Choose a dialogue with another PC user

    2. Type any 255 symbols out of 256.

    3. Click “Send

**Comment by Alyona2015** [comment]
Open LanChat v.0.8
Steps to reproduce:
1.Choose a dialogue with another PC user

2.Type any 255 symbols.

3.Click “Send”

**Comment by Alyona2015** [comment]
Open LanChat v.0.9
Steps to reproduce:
1.Choose a dialogue with another PC user

2.Type any 255 symbols.

3.Click “Send”

**Comment by Alyona2015** [comment]
Open LanChat v.0.10
Steps to reproduce:
1.Choose a dialogue with another PC user

2.Type any 255 symbols.

3.Click “Send”

**Comment by ivanmalamen** [comment]
Won't fix
